name: disable-lfs

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/action@v1
            