name: disable-lfs

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup_lfs
            - run: ls -l 
            - run: sudo apt-get install tree && tree