name: disable-lfs

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
    build:
        strategy:
          matrix:
            pip: [true, false]
        defaults:
          run:
            shell: bash -el {0}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup_lfs
            - uses: ./.github/actions/build_package
              with:
                pip: ${{ matrix.pip }}
            - run: ls -l 
            - run: sudo apt-get install tree && tree
            - run: micromamba activate yolo
            - run: python -c 'import secrets; print(secrets.token_hex())'   
            - run: python -c 'import numpy'  