name: disable-lfs

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v4
              name: get lfs repo without lfs
              with:
                repository: atharva-group/lfs-data
                path: lfs-data
                lfs: false

            - run: ls -l 
              working-directory: lfs-data

            - name: Create LFS file list
              run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
              working-directory: lfs-data
        
            - name: Restore LFS cache
              uses: actions/cache/restore@v3
              id: lfs-cache
              with:
                path: lfs-data/.git/lfs
                key: ${{ runner.os }}-lfs-${{ hashFiles('lfs-data/.lfs-assets-id') }}-v1
            
            - name: Enable LFS
              if: steps.lfs-cache.outputs.cache-hit != 'true'
              env:
                GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              run: |
                  OWNER="atharva-group"
                  REPO="lfs-data"
                  curl -L \
                    -X PUT \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer $GITHUB_TOKEN" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/$OWNER/$REPO/lfs
        
            - name: Git LFS Pull
              run: git lfs pull
              working-directory: lfs-data
              if: steps.lfs-cache.outputs.cache-hit != 'true'
              
            - name: Git LFS Checkout
              run: git lfs checkout
              working-directory: lfs-data
              if: steps.lfs-cache.outputs.cache-hit == 'true'
            
            - name: Save LFS cache if not found
              # uses fake ternary 
              # for reference: https://github.com/orgs/community/discussions/26738#discussioncomment-3253176
              if: ${{ steps.lfs-cache.outputs.cache-hit != 'true'  && always() || false }}
              uses: actions/cache/save@v3
              id: lfs-cache-save
              with:
                path: lfs-data/.git/lfs
                key: ${{ runner.os }}-lfs-${{ hashFiles('lfs-data/.lfs-assets-id') }}-v1
            
            - name: Disable LFS
              if: steps.lfs-cache.outputs.cache-hit != 'true'
              env:
                 GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              run: |
                    OWNER="atharva-group"
                    REPO="lfs-data"
                    API_URL="https://api.github.com/repos/$OWNER/$REPO/lfs"
                    AUTH_HEADER="Authorization: Bearer $GITHUB_TOKEN"
                    RESPONSE=$(curl -L -X DELETE -H "Accept: application/vnd.github+json" -H "$AUTH_HEADER" -H "X-GitHub-Api-Version: 2022-11-28" $API_URL)
                    echo $RESPONSE
            
            - run: ls -l 
              working-directory: lfs-data

            - name: Get cache sizes
              env:
                GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
              run: |
                OWNER="atharva-group"
                REPO="workflows"
                API_URL="https://api.github.com/repos/$OWNER/$REPO/actions/caches"
                AUTH_HEADER="Authorization: token $GITHUB_TOKEN"
                RESPONSE=$(curl -s -H "$AUTH_HEADER" $API_URL)
                echo "Cache sizes:"
                echo $RESPONSE
                echo $RESPONSE | jq '.actions_caches[] | {id, size_in_bytes}'


